### ISSUE TITLE
Windows Bolt with apply block in plans fails silently and logs "Something's gone terribly wrong"

### ISSUE THREAD

**Issue by kev-in-shu** [puppetlabs/bolt#2403]
## Describe the Bug
Running a plan with apply block, from a Windows Bolt Controller, fails silently .
There is only an INFO log entry appearing in bolt-debug.log

```
2020-11-25T09:05:21.567312 INFO   [] [Bolt::Executor] {"message":"Something's gone terribly wrong! STDERR is logged."}
```

## Expected Behavior
Apply blocks that work perfectly fine when run from a Linux Bolt controller should work the same way on Windows.

Also, regardless of the issue, if there is an error that's gone terribly wrong, Bolt should show the error instead of hiding it in the bolt-debug.log file.

## Steps to Reproduce
1. Create a bolt-project.yaml file with the following piece of yaml
```
---
name: boltcode
```
2. Create a file named plans/test_apply.pp with the following piece of code
```
plan boltcode::test_apply(
  TargetSpec $targets
) {
  apply($targets) {
    file {'c:/tempapplyblock':
      ensure => file
    }
  }
}
```
3. Run the plan on a target
4. Check that the standard output of Bolt shows no sign of errors like "apply catalog with 0 failures"
5. Check on the target that no resource was applied
6. Check in bolt-debug.log the "Something's gone terribly wrong" message

## Environment
 - Version: 2.35.0
 - Platform: Windows Bolt controller
 - Platform: Windows or Linux target

## Additional Context

- Debugging the issue shows that libexec/bolt_catalog writes warnings in its standard output (see below). For this reason, the resulting JSON cannot be parsed.

```
E, [2020-11-25T09:04:53.025679 #31348] ERROR -- : Facter::InternalFactManager - "\xE9" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to UTF-16LE
```

- The above warning about UTF conversion also appears systematically at the start of every bolt command run from a Windows Bolt Controller
  - So far, I saw that this warning about UTF conversion disappears when I delete the bolt-project.yaml... But I could not run my plan under these conditions

**Comment by lucywyman** [comment]
@kev I'm not able to reproduce this issue, can you post a (redacted) version of your plan, and the output from Bolt? It seems to me like something else is going wrong and causing an undiagnosed error. I could be wrong and if Puppet is returning useless information at stderr we'll probably want to figure out what is being returned and remove it rather than just ignore it.

> Also, regardless of the issue, if there is an error that's gone terribly wrong, Bolt should show the error instead of hiding it in the bolt-debug.log file.

That message is just printed from Bolt to be helpful, but it isn't obscuring anything - any errors should be logged at `error` level by Bolt, though there may be additional messages logged by Puppet that may not be logged at Bolt's default log-level for plans which is `warn`.
```
      # Any messages logged by Puppet will be on stderr as JSON hashes, so we
      # parse those and store them here. Any message on stderr that is not
      # properly JSON formatted is assumed to be an error message.  If
      # compilation was successful, we print the logs as they may include
      # important warnings. If compilation failed, we don't print the logs as
      # they are likely redundant with the error that caused the failure, which
      # will be handled separately.
      logs = err.lines.map do |line|
        JSON.parse(line)
      rescue JSON::ParserError
        { 'level' => 'err', 'message' => line }
      end
```

**Comment by lucywyman** [comment]
Thanks for raising this @kev-in-shu ! I'm asking our Facter team about it, as I don't think you should be seeing the UTF error to begin with. Rather than suppress it I'd like to see if we can fix it first.

**Comment by lucywyman** [comment]
Update: Looks like this is duplicates this Facter issue: https://tickets.puppetlabs.com/browse/FACT-2856 Devs tell me it's been fixed and will be released before the end of the year!

I'm concerned that non-JSON output was printed to stdout when the error is raised. I think the goal of this ticket is to figure out under what circumstances errors are printed to stdout instead of stderr and address that directly so this doesn't happen with other error messages.

**Comment by kev-in-shu** [comment]
Thanks @lucywyman for the feedback. It's great news that it will be fixed before the end of the year.

**Comment by lucywyman** [comment]
Hm, I'm having trouble reproducing the error. It seems like what happened was an error was raised (`[2020-11-25T09:04:53.025679 #31348] ERROR -- : Facter::InternalFactManager - "\xE9" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to UTF-16LE`), which caused the apply block to fail and print the error. I don't think there's anything for us to do here, since if stdout isn't JSON it means somethings gone wrong (like the error above).

The error itself should be fixed soon, but for now I don't think there's any behavior we need to change. Let me know if you have ideas for how to make the error message more clear @kev-in-shu! If you're ok with it, I think we'll close this and verify the fix in Facter once it's released later this month.

**Comment by kev-in-shu** [comment]
Hi @lucywyman

I think Bolt apply should more clearly fail instead of just logging things in the background. It should not be that hard since erroneous JSON output detection is already implemented. The problem is that even though bolt detected the issue, it does not show up in regular user output, and only write a log hidden in bolt-debug.log

`2020-11-25T09:05:21.567312 INFO   [] [Bolt::Executor] {"message":"Something's gone terribly wrong! STDERR is logged."}
`

It took me some time to realize it was the whole apply block that failed when I switched to running from Windows.

**Comment by kev-in-shu** [comment]
Hi,

Just wanted to let you know that I fetched the latest version of Bolt, Puppet and Facter, but I still have the issue

```

> bolt --version
2.40.2
> puppet --version
7.1.0
> facter --version
4.0.47

```

**Comment by lucywyman** [comment]
Hm, we actually just released 2.42.0 yesterday, which is the version that ships with Facter 4.0.47. Does it still happen if you upgrade to Bolt 2.42.0? I think Bolt might be using the Facter it ships with rather than another version installed on the system, and Bolt 2.40.2 shipped with Facter 4.0.38.

**Comment by kev-in-shu** [comment]
Thank you for your reply. I just installed bolt 2.42.0 and could test that the apply blocks work now.

**Comment by lucywyman** [comment]
Yay!!
