### ISSUE TITLE
Ubuntu 22.04 Support

### ISSUE THREAD

**Issue by asa1** [puppetlabs/bolt#3159]
## Use Case
Ubuntu 22.04 is an LTS release, and it has been out for 6 months now. Puppet-agent has supported 22.04 since August.

## Describe the Solution You Would Like
Ideally support for Ubuntu LTS releases as they are released.

## Describe Alternatives You've Considered
Switching back to ansible :)

**Comment by moritz-makandra** [comment]
When I try to connect to a server running Ubuntu 22.04 sshd rejects the connection:

```bash
❯➜ bolt command run "hostname" --targets 10.20.30.40
Started on 10.20.30.40..
all authorization methods failed (tried none, publickey)
Failed on 10.20.30.40:
  Authentication failed for user user@10.20.30.40
Failed on 1 target: 10.20.30.40
Ran on 1 target in 0.31 sec
```


```
sshd[49309]: userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]
```

When I use bolt with the `--native-ssh` flag the command works fine.

I guessed there is an Issue with Net::SSH but this fine as well:

```ruby
require '/opt/puppetlabs/bolt/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/'

Net::SSH.start('10.20.30.40', 'user') do |ssh|
  res = ssh.exec!("hostname")
  puts res
end
```

**Comment by asa1** [comment]
Could someone comment on if Ubuntu support is planned going forward, and if so,  when?  

Thank you

**Comment by donoghuc** [comment]
We are working on getting packages built today. Should be included in bolt 3.26.2.

**Comment by asa1** [comment]
> 

Thank you!!!

**Comment by swells-ac** [comment]
I am on bolt 3.26.2 and experiencing this issue.  The puppet servers is on 18.04 and can't connect to newly built 22.04 clients.  Yet it can with the native ssh.

**Comment by davidsandilands** [comment]
Ubuntu 22.04 has been released but to confirm @swells-ac is this still an issue you are experiencing ?

**Comment by swells-ac** [comment]
I just ran it and it is saying a fingerprint doesn't match.  Which is probably just a cache issue.  I don't get the error with native ssh option.  Host is on ubuntu 20 this only happens against the ubuntu 22 hosts.  We are still using rsa.  And the clients have been upgraded from older version.  I would say it is fixed and the error I am getting now is just from upgrading and something needs to be cleaned up.

**Comment by knorx** [comment]
I still experience this issue with bolt 3.30.0. We just managed to get this to work by updating the net-ssh version shipped with bolt. It comes (at least on windows) with 6.1.0. Doing a manual `gem update net-ssh` installed 7.2.3, which got rid of this error.
