### ISSUE TITLE
Support strong SSH KexAlgorithms/MACs

### ISSUE THREAD

**Issue by slauger** [puppetlabs/bolt#733]
A connection with bolt to a hardened SSH instance (only accepting `KexAlgorithms curve25519-sha256@libssh.org` and `MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com`) is currently not possible and fails with "could not settle on kex algorithm. 

It would be great if bolt would also support these strong kexs/macs/ciphers. 

**Output**
```
-bash# bolt task run yum --trace --verbose --nodes node01.example.tld action=upgrade 
Loading modules from /opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.1.0/bolt-modules:/etc/puppetlabs/code/environments/production/modules:/etc/puppetlabs/code/environments/production/forge:/opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/bolt-1.1.0/modules
Starting: task yum on node01.example.tld
Running task yum with '{"action"=>"upgrade", "_task"=>"yum"}' on ["node01.example.tld"]
Started on node01.example.tld...
{"node":"node01.example.tld","status":"failure","result":{"_error":{"kind":"puppetlabs.tasks/connect-error","msg":"Failed to connect to node01.example.tld: could not settle on kex algorithm","details":{},"issue_code":"CONNECT_ERROR"}}}
Failed on node01.example.tld:
  Failed to connect to node01.example.tld: could not settle on kex algorithm
Finished: task yum with 1 failure in 0.15 sec
Failed on 1 node: node01.example.tld
Ran on 1 node in 0.21 seconds
```

**Affected version**
```
-bash# rpm -qa | grep puppet-bolt
puppet-bolt-1.1.0-1.el7.x86_64

-bash# rpm -ql puppet-bolt | grep 'net-ssh-*.gemspec$'
/opt/puppetlabs/bolt/lib/ruby/gems/2.5.0/gems/net-ssh-5.0.2/net-ssh.gemspec
```

**Example SSH configuration**
```
-bash# cat /etc/ssh/sshd_config 
# File is managed by Puppet
AddressFamily any
Port 22

#HostKey /etc/ssh/ssh_host_dsa_key
#HostKey /etc/ssh/ssh_host_ecdsa_key
AcceptEnv LC_*
Banner none
ChallengeResponseAuthentication no
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
Compression no
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ed25519_key
HostbasedAuthentication no
IgnoreRhosts yes
KexAlgorithms curve25519-sha256@libssh.org
LogLevel VERBOSE
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com
MaxAuthTries 2
MaxSessions 10
MaxStartups 10:30:100
PasswordAuthentication no
PermitEmptyPasswords no
PermitRootLogin without-password
PrintMotd no
Protocol 2
Subsystem sftp /usr/libexec/openssh/sftp-server
SyslogFacility AUTHPRIV
UseDNS no
UsePAM yes
X11Forwarding no
```

**Comment by MikaelSmith** [comment]
This seems similar to https://tickets.puppetlabs.com/browse/BOLT-920, although may not be the same issue. It seems like net-ssh needs some improvements here.

**Comment by tuxmaster5000** [comment]
https://tickets.puppetlabs.com/browse/BOLT-920 looks like an problem with the key format, but in this case it will fails at an key exchange phase. So the user key file will not used in this stage.

**Comment by FredericLespez** [comment]
According to https://github.com/net-ssh/net-ssh/blob/master/CHANGES.txt
Support for curve25519sha256 has been added in net-ssh 6.0.0beta1.

**Comment by slauger** [comment]
All good things are worth waiting for. :wink:

**Comment by nicklewis** [comment]
I _believe_ this release of Bolt will support `curve25519-sha256@libssh.org` but not the EtM HMACs yet. We'll need to wait for net-ssh 6.1.0 to come out for that.

**Comment by slauger** [comment]
@nicklewis I'll can give it a try once the rpm/deb packages for 2.7.0 are available.

**Comment by tuxmaster5000** [comment]
To day I update to 2.7.0 but the problem are the same :(
On the server site:

> sshd[53040]: Unable to negotiate with XXXX port 41570: no matching key exchange method found. Their offer: ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-
group-exchange-sha256,diffie-hellman-group14-sha1 [preauth]

On the bolt site:

> Server kex preferences: curve25519-sha256@libssh.org
>   Client kex preferences: ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1

Nothing with curve25519...

**Comment by beechtom** [comment]
@tuxmaster5000 @slauger It looks like we missed a required dependency to enable support for `curve25519`. If you install the `x25519` gem, you _should_ be able to authenticate.

```
$ /opt/puppetlabs/bolt/bin/gem install --user-install x25519
```

Lmk if this solves your issue. We'll also work on getting this added to a future release.

**Comment by tuxmaster5000** [comment]
/opt/puppetlabs/bolt/bin/gem install --user-install x25519

> Fetching: x25519-1.0.8.gem (100%)
> WARNING:  You don't have /home/XXXX/.gem/ruby/2.5.0/bin in your PATH,
> 	  gem executables will not run.
> Building native extensions. This could take a while...
> Successfully installed x25519-1.0.8
> Parsing documentation for x25519-1.0.8
> Installing ri documentation for x25519-1.0.8
> Done installing documentation for x25519 after 0 seconds
> 1 gem installed

Yes this will help, but now another error is thrown:
Server encryption_client preferences: chacha20-poly1305@openssh.com,aes256-gcm@openssh.com
Client encryption_client preferences: aes256-ctr

**Comment by slauger** [comment]
> We'll also work on getting this added to a future release.

So can we reopen this this issue?

**Comment by lucywyman** [comment]
@slauger Does it work with the gem installed?

**Comment by beechtom** [comment]
@tuxmaster5000 It looks like your client does not use a supported encryption algorithm that is also used by the server. `net-ssh` supports a more limited set of algorithms, which you can find here: https://github.com/net-ssh/net-ssh#encryption-algorithms-ciphers.

If it's an option, adding the `aes256-ctr` algorithm to your server-side configuration should fix that error.

**Comment by slauger** [comment]
> @slauger Does it work with the gem installed?

Without the additional x25519 gem:

```
root@foreman01:~ 
-bash# bolt task run yum --trace --verbose --targets jenkins01.example.de action=upgrade 
Started on jenkins01.example.de...
Failed on jenkins01.example.de:
  Failed to connect to jenkins01.example.de: could not settle on kex algorithm
  Server kex preferences: curve25519-sha256@libssh.org
  Client kex preferences: ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
Failed on 1 target: jenkins01.example.de
Ran on 1 target in 0.44 sec
```

With the additional x25519 gem installed:

```
root@foreman01:~ 
-bash# /opt/puppetlabs/bolt/bin/gem install --user-install x25519
Fetching: x25519-1.0.8.gem (100%)
WARNING:  You don't have /root/.gem/ruby/2.5.0/bin in your PATH,
	  gem executables will not run.
Building native extensions. This could take a while...
Successfully installed x25519-1.0.8
Parsing documentation for x25519-1.0.8
Installing ri documentation for x25519-1.0.8
Done installing documentation for x25519 after 0 seconds
1 gem installed

root@foreman01:~ 
-bash# bolt task run yum --trace --verbose --targets jenkins01.example.de action=upgrade 
Started on jenkins01.example.de...
Failed on jenkins01.example.de:
  Failed to connect to jenkins01.example.de: could not settle on hmac_client algorithm
  Server hmac_client preferences: hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com
  Client hmac_client preferences: hmac-sha2-512,hmac-sha2-256,hmac-sha1
Failed on 1 target: jenkins01.example.de
Ran on 1 target in 0.3 sec
```

Well, the error message changed, but the problem is not yet resolved. Seems like that there a still problems with the HMACs. The target machine is an CentOS 7 with the SSH configuration from above.

**Comment by tuxmaster5000** [comment]
It looks like, the net-ssh module are more then 5 years behind openssh. This result in an big problem for bolt in environments, where an higher security level is needed.

**Comment by slauger** [comment]
> It looks like, the net-ssh module are more then 5 years behind openssh. This result in an big problem for bolt in environments, where an higher security level is needed.

As long as secure ssh connections doesn't work, bolt isn't a real competitor for ansible in my opinion. I knew net-ssh before and was therefore very skeptical about bolt.

I have had similar experiences with chef and inspec (also based on ruby and net-ssh).

**Comment by nicklewis** [comment]
I agree that this is a major problem.

We've discussed for quite a while the option of managing connections by shelling out to `ssh` to help accommodate more obscure use cases that net-ssh can't handle (2 factor auth, etc). We didn't prioritize it because those use cases were in fact obscure. But "modern crypto algorithms" is not obscure by any stretch. If net-ssh is simply moving too slowly to stay secure, we can't rely on net-ssh. Fortunately, we've recently done some work that makes an external SSH option much easier to implement, so we're now starting on an external SSH implementation. You can follow 
 along on #1780.

My hope is that net-ssh will be able to catch back up with modern crypto (maybe we can help there) and we can rely on external SSH only for the edge cases, but as I don't have reason to believe anyone is actively working on that, we need an alternate solution _now_.

**Comment by nicklewis** [comment]
@slauger I actually missed part of the output that you posted before. The EtM HMAC algorithms were removed from net-ssh 6.0.1 due to a bug and will be back in 6.1.0 which should hopefully be out soon.

I mixed up the encryption algorithm issue with the HMAC algorithm issue. `curve25519-sha256` for kex and EtM HMACs should be supported soon. `chacha20-poly1305@openssh.com` for encryption is the one that doesn't appear to be on the horizon and is what's motivating us to work on the external SSH option.
